### ISSUE TITLE
Is PoolTeam.pool redundant?

### ISSUE THREAD

**Issue by jonahgreenthal** [quizbowl/schema#100]
A `Pool` contains 0 or more `PoolTeam`s. A `PoolTeam` has a reference back to `Pool`. The latter is unnecessary, right?

**Comment by jonahgreenthal** [comment]
(@rhentzel pointed this out)

**Comment by puls** [comment]
Redundant, sure. Probably just an artifact about visualizing this in our heads as a join table.

**Comment by jonahgreenthal** [comment]
Can we remove it without having to do a major version bump? That also seems, in a soft sense, unnecessary.

**Comment by puls** [comment]
Not if you want to strictly adhere to semantic versioning. But would removing it break anything anywhere? I doubt it.

**Comment by jonahgreenthal** [comment]
It won't break anything. I'm inclined to just kill it and bump the minor version.
