### ISSUE TITLE
Optional index or position field in MatchQuestionBuzz

### ISSUE THREAD

**Issue by alopezlago** [quizbowl/schema#64]
I think we should have an optional index or position field in MatchQuestionBuzz to track where a buzz occurred. This could either be based on the position of the first character buzzed in, or the word number.
The default for this value could be -1, indicating that the position was not tracked for this buzz.

**Comment by puls** [comment]
What about a `BuzzPosition` that includes a character index, a word index, and/or a time index?

Also, you wouldn't default to `-1`, you'd just leave an optional field out.

**Comment by jonahgreenthal** [comment]
How should time index be formatted / what should it be relative to?

Should we allow the specification of a clue number? Obviously this would have to be well-defined elsewhere, but it seems plausible.

We should allow (but not require) the actual word being buzzed upon to be specified.

Should we distinguish between "buzzed upon hearing the last word" and "buzzed after the question ended, but not immediately"? (If so, how?)

**Comment by puls** [comment]
For a time index, I'd put a start time on the `MatchQuestion` and a timestamp on the MatchQuestionBuzz.

For a word index, I'd do just a simple word index, as a character index is too granular and a clue index is rightly defined elsewhere.

(I could see future fields for question content defining clues by word index and being able to cross reference that.)

I'm dubious on the utility of tracking how long after the end of a question a buzz happened.

**Comment by hftf** [comment]
Although the definition of clue boundaries is not in scope, I think it would help if a standard definition of word (or maybe a non-normative recommendation) were included in the schema.

Example implementation (after a few years of iteration): https://github.com/hftf/oligodendrocytes/blob/ada0a231cbff5ac121af2aef00fe4d6fa4aef837/transformers/f-html-to-w-html.js#L61

**Comment by puls** [comment]
I'm fine with a further definition of a "word" as a "run of non-whitespace characters".

**Comment by jonahgreenthal** [comment]
How about "run of consecutive characters that are neither whitespace, nor any sort of dash, nor a power mark"? I realize this is getting pretty finicky, but I feel like we want to be able to distinguish, e.g., which name people buzz on in the Johnson-Corey-Chaykovsky reaction. (And a power mark just doesn't seem like a word to me.)

**Comment by hftf** [comment]
I don’t have a strong opinion, but I would lean more toward the simpler implementation I linked above (words are delimited by whitespace, but words that are just symbols are not words).

I think more granularity is not really necessary as there will always be false positive and false negatives. I can think of many uses of hyphens or dashes that I would consider to be single “words” (E-flat, X-ray, p–n junction, 5–4 decision, NO<sub>2</sub><sup>–</sup>, 10<sup>–9</sup>), and many other symbols that can also be used to separate “words” (Either/Or, Silence=Death, 2+2+2+3 pattern, 3:2:1 ratio).

**Comment by jonahgreenthal** [comment]
Fair enough, though my reaction to those examples is "Okay, maybe it should be 'run of consecutive alphanumeric characters.'" (I know that still has part of the hyphen/dash problem you mention.)

I'm also very okay with not defining "word" here.

**Comment by hftf** [comment]
I think a definition is within the scope of this schema “about the necessary data to pass back and forth and get a full recounting of what happened.” If there isn’t a somewhat stable definition of “word,” then that could make interchange more difficult.

Clue boundaries aren’t systematic so it makes sense to encode such a field separately (such as an array of substrings or indexes). But word boundaries are mostly systematic, so it would be redundant to store an array of words or encode slight behavior differences in how applications split words.
