### ISSUE TITLE
Record scores on individual bonus parts

### ISSUE THREAD

**Issue by jonahgreenthal** [quizbowl/schema#65]
Especially now that NAQT's scoresheet does so, we should represent scoring on individual bonus parts rather than for the bonus as a whole.

Here's my first stab at how to represent it: In `MatchQuestion`, remove `bonus_points` and `bounceback_bonus_points`, and change to `bonus_parts`, which is an array of `BonusPart` objects, and may be omitted if the question type doesn't award a bonus.

Each `BonusPart` has `points` (number; required) and `bounceback_points` (number; may be omitted if bonuses don't bounce back)

For "normal bonuses" in which there are distinct parts in a definite order, each part gets its own `BonusPart`, and — at least in every format I'm familiar with — `bounceback_points` can only be nonzero if points is zero. For weird cases like "name any _n_ of the _m_ things", just treat the whole bonus as a single `BonusPart`, and then you might report something like `{points: 20, bounceback_points: 10}`.

**Comment by puls** [comment]
Sure. Is there any way to name a bonus part that more closely aligns it with `MatchQuestionBuzz`?

(Also: removing a field would be a major version bump. We could avoid that by allowing either `bonus_points` or `bonus_parts` but not both.)
