### ISSUE TITLE
Match should accommodate using different packets than specified in Round

### ISSUE THREAD

**Issue by jonahgreenthal** [quizbowl/schema#66]
Sometimes an individual game might use different packets than were used for most games that round — for instance, due to a mistake, fixing an earlier mistake, or accommodating a team that had written the packet used for most games that round.

We should accommodate this by putting a `custom_packets` field on Match, which is used only to override the `Round.packets` field.

**Comment by puls** [comment]
I like this, but I'd just call it `Match.packets`. It's optional, and if omitted one can assume the value from `Round.packets`.
