### ISSUE TITLE
Default assumption for Round.packets

### ISSUE THREAD

**Issue by jonahgreenthal** [quizbowl/schema#67]
Should we specify that if `Round.packets` is omitted, it is assumed that precisely one packet was used, and it's the packet whose number is the same as the round number? I guess this requires the packet set to already be known; should that be specified on `Tournament`?

**Comment by hftf** [comment]
To me it seems more logical and easy to just explicitly indicate the packet, rather than go through extra hoops as described in #66 just to avoid repeating a number that has to be present anyway.

**Comment by jonahgreenthal** [comment]
I don't understand what you mean. I'm proposing a standard explanation for what an absence of data means, not asking anyone to jump through hoops or enter extra data.

**Comment by puls** [comment]
This doesn't seem necessary to me, but it also can't hurt. I can't think of any other assumption that makes sense that could cause confusion here.

(Also, `Tournament.question_set` already exists.)
