### ISSUE TITLE
Improve Tournament.level and difficulty

### ISSUE THREAD

**Issue by jonahgreenthal** [quizbowl/schema#75]
These current fields are poorly named and have strange options.

I propose we replace them with these fields and choices:
Audience: elementary_school, middle_school, high_school, community_college, college, open, other
Level: novice, regular, nationals, other
Content: general_academic, specialized_academic, trash, other

Any objections?

What's the proper version number bump for this sort of change? We're adding fields, removing a field, and changing the meaning and choices of a field.

**Comment by puls** [comment]
This would be a major version bump.
