### ISSUE TITLE
Include category and/or question-identifying information

### ISSUE THREAD

**Issue by jonahgreenthal** [quizbowl/schema#79]
My first instinct is that this belongs on `MatchQuestion`, but there may be tricky issues to deal with when a question is replaced for one side. Maybe it normally goes on `MatchQuestion`, but `MatchQuestionBuzz` can override?

Note that this field may have significant implications for question security.

**Comment by puls** [comment]
Adding a `Question` type (with fields like `category` and `text` and `type` of "tossup" or "bonus") makes sense. `MatchQuestion` could have a `question` and a `replacement_question` or something like that.

**Comment by jonahgreenthal** [comment]
Having `MatchQuestion.replacement_question` leaves open the question of who was eligible to answer the replacement question (it could be any nonempty subset of the `MatchTeams`). But `MatchQuestionBuzz` doesn't work either, because if no eligible team buzzes, we'd have no record of the replacement question. Sigh. Maybe `MatchQuestion.replacement_question` takes a `Question` with an additional array of eligible `MatchTeam`s. Does that seem right to you?
